M48
; DRILL file {KiCad 7.0.1} date Mon Nov 20 00:05:40 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-20T00:05:40-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X105.5Y-130.045
X111.28Y-130.045
T2
X86.79Y-84.06
X88.022Y-132.65
X168.07Y-64.85
X201.56Y-133.92
T0
M30
